Propagate tintColor if window not available
ResearchKit/ResearchKit pull request #1519
Opened 2022-11-14 19:47 UTC by cbaker6

When an app is using the SwiftUI lifecycle (App protocol) and doesn't use the scene delegate, the tintColor isn't properly inherited in surveyViewController in OCKSurveyTaskViewController from the calling view. This occurs with the latest commit on the main of CareKit and the latest commit on the main of ResearchKit (https://github.com/ResearchKit/ResearchKit/commit/a89059f5dc2a91f36785b184f914b5e5fdb05877)

More info here: https://github.com/carekit-apple/CareKit/pull/676

2022-11-14 19:53 UTC, cbaker6 commented
I believe this may address this issue as well: https://github.com/ResearchKit/ResearchKit/issues/1494#issuecomment-1156819746

2022-11-17 23:43 UTC, louie-apple commented
Hi Corey, 

Thank you for submitting this. We are looking at this, and will have some feedback soon.

2022-11-21 23:15 UTC, cbaker6 commented
@louie-apple not a problem, let me know if you need me to make any adjustments.

2022-11-28 17:41 UTC, louie-apple commented
Hi Corey, 

Our team took a look and your changes are looking good. Thank you for sharing these with us. 
We would like to suggest a few different changes. 

We would suggest creating a new method in the `ORKHelpers_Internal` class called 
`UIColor *ORKViewTintColor(UIView *view);`

With the implementation being 
`UIColor *ORKViewTintColor(UIView *view) {
    UIColor *existingTintColor = view.tintColor ? : [UIColor systemBlueColor];
    UIColor *tintColor = ORKWindowTintcolor(view.window) ? : existingTintColor;

    return tintColor;
}`

That way in the `ORKTaskViewController` all you would have to do is call 
`UIColor *tintColor = ORKViewTintColor(self.view);`

2022-11-28 17:44 UTC, louie-apple requested changes

2022-11-28 17:44 UTC, louie-apple commented on ResearchKit/Common/ORKTaskViewController.m
> +    UIColor *tintColor = ORKWindowTintcolor(self.view.window) ? : self.view.tintColor;
```suggestion
        UIColor *tintColor = ORKViewTintColor(self.view);
```

2022-11-28 20:29 UTC, cbaker6 commented
@louie-apple great suggestions! I've added the changes and will test them shortly.

Let me know if you see something I missed.

2022-11-29 02:33 UTC, cbaker6 commented
Update: I've tested this and it works

2022-11-30 04:21 UTC, louie-apple commented
> Update: I've tested this and it works

Hi @cbaker6 ,

Thank you for adding that, we also reviewed it and it looks good on our end!

2022-11-30 04:21 UTC, louie-apple approved these changes

2022-11-30 04:22 UTC, merged

2023-02-13 20:17 UTC, louie-apple commented
Hi @cbaker6,

We recently pushed a new release, 2.2.9-dev (https://github.com/ResearchKit/ResearchKit/releases/tag/2.2.9-dev) on main. Would you please pull this release and see if your tint fix still works as expected?

2023-02-13 22:26 UTC, cbaker6 commented
@louie-apple thanks for pinging me on this. It appears to still work.

There is an issue leftover from before this PR (I'm assuming I missed this in my earlier PR) with `ORKLearnMoreItem` in which the link and the `ORKLearnMoreItem` view has the wrong `tintColor` basically it always uses the default blue. I haven't had a chance to look into it, but I see it when constructing a `ORKLearnMoreInstructionStep` and adding a `ORKBodyItem` with `ORKLearnMoreItem` inside of a `ORKOrderedTask`. I believe the link color of "Learn More" and the `tintColor` of the view is incorrect. You can see the issue in screenshots below:

![Simulator Screen Shot - iPhone 14 Pro - 2023-02-13 at 17 24 41](https://user-images.githubusercontent.com/8621344/218588316-fae0dcfa-9529-4557-a840-748fabc3ea67.png)

![Simulator Screen Shot - iPhone 14 Pro - 2023-02-13 at 17 25 07](https://user-images.githubusercontent.com/8621344/218588395-146e5c67-eeb4-4d14-9522-3da67932e528.png)